### ISSUE TITLE
Freno between multiple regions

### ISSUE THREAD

**Issue by sirupsen** [github/freno#53]
Hey @shlomi-noach! After chatting with @samlambert last week, I'm looking a bit at Freno and was hoping you'd answer a couple of questions about using Freno between regions.

Currently we have a mechanism inside Rails that does essentially the same as the sample Freno configs: cheecks replication lag through `pt-heartbeat` and running InnoDB threads—throttling itself if they exceed a threshold. We cache these results aggressively in Memcached (similar to https://github.com/github/freno/pull/51) and the client. I should note that our primary source of lag are migrations in Rails, i.e. large tasks that iterate over a large amount of records to update them ('maintenance tasks') as well as schema changes (LHM, presently, but looking at `gh-ost`).

However, recently we've started seeing more cases where other _regions_ are lagging _more_ than the latency to the region with the writer. This can be due to a variety of factors, but I'm unsure that our present assumption of: if the slave in the current region can catch up, so can the slave in the other region. This can be due to a variety of factors, difference in hardware, hiccups, etc., but with our increasing number of shards I believe we'll have to accept throttling across regions.

Doing this inside Rails with cross-region connections is _sketchy_ so say the least, which caused me to look at Freno. However, the way I'm reading the documentation, it would require the Freno master  in a single region to connect to all other regions' MySQLs. Is that correct, and is this something you do? It would also mean running multiple Freno clusters unless we'd go cross-dc for Freno, when running `active:active` (as we are, presently). Service discovery is often scoped to a datacenter, so this can get a bit awkward. When first looking at Freno, I was hoping that the agents would be able to run in multiple data-centers with Raft being used for storing the data, rather than a single leader with the data in memory.

Just as an aside, are you seeing Freno long-term turn into a kind of [Doorman](https://github.com/youtube/doorman)? We've been searching for something like this for a while to set global throttling rates for accessing various data-stores. Doorman has some really nifty features, would be curious what you think. Would be happy to chat in Slack about this too.

Cheers!

**Comment by sroysen** [comment]
There are multiple possible reasons for some slaves to lag more than others.

For the most part we can do nothing to ameliorate them now.

We should be able to fix some of them once we move to shorter replications chains (with all the local slaves connecting to the local master), which is going to be feasible once we have Orchestrator in place in the cloud.
Things are also going to improve once we start using multithreaded replication in the cloud. Right now the net effect of it on the read slaves at the lowest level of the replication chain, is not going to be as effective: The farther away a node is from the master, the less parallelism is going to be able to apply to the transactions that it needs to execute.

Some of the reasons:

1. ETLs hitting the secondary read-slave. We always asked the data teams to hit the read slaves in the secondary DCs to reduce the load in the primary DC. The net effect of ETLs is not only in terms of query load, but also in terms of what data is kept warm in the innodb buffer pool (data access patterns for ETLs usually push old btree pages into the buffer pool that are not necessarily useful for writes, which is what the slaves do need).
2. The read slave in the secondary DC is always one replication step lower than the read slave in the primary DC. Since replication lag is cumulative (the lower you are in the replication chain, the higher your lag is going to be, because you need to wait for all the nodes upstream to apply the changes) the secondary read slave is going to have more lag than the read slave in the the primary DC.
3. Under high load conditions (generating a sizeable amount of binlogs per minute) things like network latency cross DCs to transfer those binlogs start to have an effect. Probably the same can be said for the network latency across regions in the cloud. This was an issue multiple times in the past when we had less bandwidth in the cross DCs VPNs.
4. Unpredictable differences in IO performance due to different wear of the SSD drives used for the local RAID10 arrays (for the DCs).

**Comment by shlomi-noach** [comment]
Hi 👋 !

> Currently we have a mechanism inside Rails that does essentially the same as the sample Freno configs: cheecks replication lag through pt-heartbeat and running InnoDB threads—throttling itself if they exceed a threshold. We cache these results aggressively in Memcached (similar to #51) and the client.

Sounds familiar. 
> However, the way I'm reading the documentation, it would require the Freno master in a single region to connect to all other regions' MySQLs. Is that correct, and is this something you do? It would also mean running multiple Freno clusters unless we'd go cross-dc for Freno, when running active:active (as we are, presently). Service discovery is often scoped to a datacenter, so this can get a bit awkward. When first looking at Freno, I was hoping that the agents would be able to run in multiple data-centers with Raft being used for storing the data, rather than a single leader with the data in memory.

All good points, and I've considered the same.
Right now the design is that the (single) leader is the one to run all probing.
Cross DC probing are problematic not only because of traffic but also in the sense that the query`freno` issues expect high precision of replication lag, but the latency of the query itself, and by the time the response returns to `freno`, may cause the result to be significantly off.

My current thought/design for cross-DC throttling is to have a separate `freno` clusters in each DC. Each cluster will only probe DC-local boxes. Thus, `freno` will always have low-latency queries and more accurate results. Aggregations will be more accurate. 
It would be the burden of the client to check on two (or more?) `freno` clusters and to get the `OK` from all of them.

This design also conveniently allows you to setup different thresholds to different DCs. For example, you'd allow lag of `1.0s` on your primary DC, and a lag of `2.0s` on a remote DC.

> I'm unsure that our present assumption of: if the slave in the current region can catch up, so can the slave in the other region. 

The remote replicas will suffer from more latency, but throughput _should be the same_. Of course, they may serve different production read-load, and that's a major factor. They will occasionally be susceptible to cross-DC network glitches, and those can be local or long-ongoing events.

> Just as an aside, are you seeing Freno long-term turn into a kind of Doorman?

Hopefully you've read this doc page? https://github.com/github/freno/blob/master/doc/compare-doorman.md
I do not intend to turn `freno` into more `doorman`-like. `doorman` implies knowing up-front what your _capacity_ is. `freno` is just greedy and throttles when reality says it should stop.

You're talking about rate-limiters which are an in-between concept and of a different type. You;d want to add rate-limiting _on top_ of already existing lag checks. (BTW `freno` is not strictly about mysql lag, you can use any query to determine yes/no response).
Rate limiting is interesting, but then `freno` would need to get a lot more information from the app, such as "what exactly do you intend to do with the database? Write how many rows? Delete anything? Specific user ID/token?" -- and than do a specific kind of math given such input ; managing tokens in-house etc. I suspect these would be more difficult to generalize this as an open source projects and it will have to be tightly bound to a particular app's use case.
I'm happy to discuss further.

**Comment by shlomi-noach** [comment]
@sirupsen if the above satisfies your question, please consider closing this Issue.
